# Generated by Django 4.2.5 on 2023-11-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.RemoveField(
            model_name='cupondescuento',
            name='codigo',
        ),
        migrations.AddField(
            model_name='cupondescuento',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cupondescuento',
            name='descuento',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
