# Generated by Django 4.2.5 on 2023-11-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_profile_options_remove_cupondescuento_codigo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cupondescuento',
            options={'verbose_name': 'Cupon', 'verbose_name_plural': 'Cupones'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='cupones_descuento',
            field=models.ManyToManyField(blank=True, related_name='cupones', to='portal.cupondescuento'),
        ),
    ]
