# Generated by Django 4.2.5 on 2023-11-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=800, verbose_name='descripcion'),
        ),
    ]
