# Generated by Django 4.2.5 on 2023-11-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='product_img', verbose_name='imagen'),
        ),
    ]
